### PR TITLE
fixes, upgrades httparty, add support for ruby 2.2.1

### PR DESCRIPTION
**Pull request by orenf**
removes support for ruby 1.9.2 and 1.8.7
upgrades httparty
runs on ruby 2.2.1
fixes failing specs
APIError message now returns valid Invoice object

### CODE REVIEW

**Comment by adamfortuna** [comment]
Nice job! I'll go ahead and merge this one in. :)

**Comment by adamfortuna** [comment]
Ok, it's all set and up on Ruby Gems now. :) https://rubygems.org/gems/avalara/versions/0.1.1

Thanks for the help getting the specs passing. Nice to see it as green again on the front main readme again.

**Comment by orenf** [comment]
Thank you so, so much @adamfortuna

**Comment by orenf** [comment]
I'm wondering why your latest changes are causing travis to error out?
Want me to look into it?

**Comment by adamfortuna** [comment]
Ahh i think i know what's up. Looks like the spec is wrong for my bump.

**Pull request merged**
