### PR TITLE
Add address validation API

### PR DESCRIPTION
**Pull request by Tonkpils**

### CODE REVIEW

**Comment by Tonkpils** [comment]
@adamfortuna would you mind peeking at this?

**Comment by adamfortuna** [comment]
Ah yeah, sorry about the delay on this one. Not actively using this gem, but this looks good to me. 👍

**Comment by Tonkpils** [comment]
@adamfortuna I'd be happy to help maintain it if you're interested. We use it at my company, we may switch to the official Avalara gem but until then we need to support this one.

**Comment by adamfortuna** [comment]
Ohh yeah, that'd be pretty awesome actually. I just published this up to rubygems as v0.2.0 for now and added you as a collaborator. If you could email me (my email's in gemspec) your rubygems email address, I could add you as an owner on there as well!

I'd definitely feel comfortable with you reviewing/merging any pull requests as well, as I think you'd be closer to the user on this than me. In other words -- I trust you. :)

**Pull request merged**
